import type { Announcement, Comment, Post, User } from './types'

export const mockUsers: User[] = [
  {
    id: 'u1',
    name: 'Ava Chen',
    email: 'avachen@campus.edu',
    avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=ava',
    role: 'admin',
    joinedAt: '2023-09-02',
    lastActive: '2025-02-10',
    status: 'active',
    posts: 84,
    comments: 412,
    followers: 980,
    bio: '负责论坛秩序与活动发布，热爱摄影与路跑。',
    tags: ['校学生会', '传媒学院'],
  },
  {
    id: 'u2',
    name: 'Leo Wang',
    email: 'leowang@campus.edu',
    avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=leo',
    role: 'student',
    joinedAt: '2023-10-10',
    lastActive: '2025-02-12',
    status: 'banned',
    posts: 12,
    comments: 55,
    followers: 120,
    bio: '创客社成员，喜欢分享科技资讯与二手数码。',
    tags: ['创客社', '数码'],
  },
  {
    id: 'u3',
    name: 'Lydia Song',
    email: 'lydia.song@campus.edu',
    avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=lydia',
    role: 'student',
    joinedAt: '2024-01-08',
    lastActive: '2025-02-14',
    status: 'active',
    posts: 46,
    comments: 220,
    followers: 304,
    bio: '社团招新负责，关注校园活动与策划。',
    tags: ['社团招新', '活动策划'],
  },
  {
    id: 'u4',
    name: 'Mason Gu',
    email: 'mason.gu@campus.edu',
    avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=mason',
    role: 'teacher',
    joinedAt: '2022-11-18',
    lastActive: '2025-02-11',
    status: 'active',
    posts: 24,
    comments: 128,
    followers: 420,
    bio: '软件工程课程教师，维护课堂讨论区。',
    tags: ['软件工程', '课堂讨论'],
  },
  {
    id: 'u5',
    name: 'Nora Yu',
    email: 'nora.yu@campus.edu',
    avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=nora',
    role: 'student',
    joinedAt: '2024-03-30',
    lastActive: '2025-02-09',
    status: 'active',
    posts: 31,
    comments: 162,
    followers: 189,
    bio: '热爱公益与志愿活动，偶尔发布失物招领。',
    tags: ['志愿', '失物招领'],
  },
  {
    id: 'u6',
    name: 'Oscar Lin',
    email: 'oscar.lin@campus.edu',
    avatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=oscar',
    role: 'student',
    joinedAt: '2024-06-11',
    lastActive: '2025-02-08',
    status: 'active',
    posts: 15,
    comments: 74,
    followers: 142,
    bio: '喜欢分享摄影作品与社团活动花絮。',
    tags: ['摄影', '艺术学院'],
  },
]

export const mockPosts: Post[] = [
  {
    id: 'p1',
    title: '校运会志愿者总结与反馈',
    author: 'Ava Chen',
    authorId: 'u1',
    category: '校园活动',
    tags: ['志愿', '活动'],
    status: 'pinned',
    views: 4258,
    comments: 126,
    createdAt: '2024-11-02',
    heat: 98,
    summary: '收集各学院志愿者反馈，整理改进事项与表彰名单。',
  },
  {
    id: 'p2',
    title: '二手图书包邮合集｜计算机&设计类',
    author: 'Leo Wang',
    authorId: 'u2',
    category: '二手交易',
    tags: ['二手', '教材'],
    status: 'hidden',
    views: 912,
    comments: 43,
    createdAt: '2025-01-05',
    heat: 66,
    summary: '整合近期二手教材供给，含价格与品相说明。',
  },
  {
    id: 'p3',
    title: '春季社团联合招新｜时间表与展位',
    author: 'Lydia Song',
    authorId: 'u3',
    category: '社团招新',
    tags: ['社团', '招新'],
    status: 'normal',
    views: 3102,
    comments: 205,
    createdAt: '2025-02-01',
    heat: 91,
    summary: '发布春季招新时间轴、展位地图及报名入口。',
  },
  {
    id: 'p4',
    title: '失物认领｜图书馆拾到校园卡',
    author: 'Nora Yu',
    authorId: 'u5',
    category: '失物招领',
    tags: ['失物招领'],
    status: 'normal',
    views: 512,
    comments: 14,
    createdAt: '2025-02-10',
    heat: 49,
    summary: '图书馆三楼拾到校园卡，请失主私信确认信息后领取。',
  },
  {
    id: 'p5',
    title: '周末校车拼车拼单集合',
    author: 'Oscar Lin',
    authorId: 'u6',
    category: '拼车拼单',
    tags: ['拼车', '出行'],
    status: 'normal',
    views: 754,
    comments: 32,
    createdAt: '2025-02-07',
    heat: 57,
    summary: '整理周末往返机场与市区的拼车需求，统一沟通。',
  },
]

export const mockComments: Comment[] = [
  {
    id: 'c1',
    postId: 'p1',
    postTitle: '校运会志愿者总结与反馈',
    author: 'Lydia Song',
    authorId: 'u3',
    content: '建议加一条志愿者保险流程说明，方便新生参考。',
    createdAt: '2025-02-11 09:24',
    likes: 34,
    status: 'visible',
  },
  {
    id: 'c2',
    postId: 'p2',
    postTitle: '二手图书包邮合集｜计算机&设计类',
    author: 'Ava Chen',
    authorId: 'u1',
    content: '请补充每本书的版本与缺页情况，方便管理审核。',
    createdAt: '2025-02-08 14:10',
    likes: 18,
    status: 'visible',
  },
  {
    id: 'c3',
    postId: 'p3',
    postTitle: '春季社团联合招新｜时间表与展位',
    author: 'Oscar Lin',
    authorId: 'u6',
    content: '摄影社周三下午有作品展，欢迎大家围观。',
    createdAt: '2025-02-12 19:02',
    likes: 42,
    status: 'visible',
  },
  {
    id: 'c4',
    postId: 'p4',
    postTitle: '失物认领｜图书馆拾到校园卡',
    author: 'Leo Wang',
    authorId: 'u2',
    content: '请注明卡号后四位，避免误领。',
    createdAt: '2025-02-10 10:11',
    likes: 6,
    status: 'removed',
  },
  {
    id: 'c5',
    postId: 'p5',
    postTitle: '周末校车拼车拼单集合',
    author: 'Nora Yu',
    authorId: 'u5',
    content: '周六晚 19:00 校门口有空出两个座位，先到先得。',
    createdAt: '2025-02-09 08:44',
    likes: 21,
    status: 'visible',
  },
  {
    id: 'c6',
    postId: 'p3',
    postTitle: '春季社团联合招新｜时间表与展位',
    author: 'Mason Gu',
    authorId: 'u4',
    content: '请在帖子内附上展位平面图与报名表链接。',
    createdAt: '2025-02-12 08:31',
    likes: 15,
    status: 'visible',
  },
]

export const mockAnnouncements: Announcement[] = [
  {
    id: 'a1',
    title: '系统维护通知',
    content: '论坛将在 2 月 16 日 00:00-02:00 进行数据库维护，请提前保存草稿。',
    status: 'published',
    pinned: true,
    hidden: false,
    createdAt: '2025-02-05',
    updatedAt: '2025-02-12',
  },
  {
    id: 'a2',
    title: '春季社团招新总览',
    content: '集中发布各社团招新流程、面试地点与时间表。',
    status: 'published',
    pinned: false,
    hidden: false,
    createdAt: '2025-02-01',
    updatedAt: '2025-02-10',
  },
  {
    id: 'a3',
    title: '失物招领规则更新',
    content: '新增实名登记与拍照留档要求，减少重复认领。',
    status: 'draft',
    pinned: false,
    hidden: true,
    createdAt: '2025-02-09',
    updatedAt: '2025-02-13',
  },
  {
    id: 'a4',
    title: '私信与消息提醒优化',
    content: '私信支持附件上传，新增未读消息聚合，以便及时回复。',
    status: 'published',
    pinned: false,
    hidden: false,
    createdAt: '2025-02-03',
    updatedAt: '2025-02-11',
  },
]
